language: node_js

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: false
    - os: osx

node_js:
  - "10"

cache:
  directories:
    - node_modules

script:
  - npm run lint
  - npm run test
  - npm run build
